In [5]:
import numpy as np

In [6]:
#Создание массивов
print("=== 1. Создание массивов ===")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros((3, 3))
arr3 = np.ones((2, 4))
arr4 = np.random.rand(2, 3)

print("arr1:", arr1)
print("arr2:\n", arr2)
print("arr3:\n", arr3)
print("arr4:\n", arr4)

=== 1. Создание массивов ===
arr1: [1 2 3 4 5]
arr2:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
arr3:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arr4:
 [[0.37230249 0.92375674 0.91591229]
 [0.93341994 0.37127137 0.87793392]]


In [7]:
#Shape и dtype
print("=== 2. Shape и dtype ===")
print("arr1 shape:", arr1.shape, "dtype:", arr1.dtype)
print("arr2 shape:", arr2.shape, "dtype:", arr2.dtype)

=== 2. Shape и dtype ===
arr1 shape: (5,) dtype: int64
arr2 shape: (3, 3) dtype: float64


In [8]:
#Индексирование и срезы
print("=== 3. Индексирование и срезы ===")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("matrix:\n", matrix)
print("matrix[0,1]:", matrix[0,1])
print("matrix[1:3, :]:\n", matrix[1:3, :])

=== 3. Индексирование и срезы ===
matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix[0,1]: 2
matrix[1:3, :]:
 [[4 5 6]
 [7 8 9]]


In [9]:
#Операции и статистики
print("=== 4. Простые операции ===")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a + b:", a + b)
print("a * 2:", a * 2)

print("=== 5. Статистики ===")
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("mean:", np.mean(data))
print("std:", np.std(data))
print("sum:", np.sum(data))

=== 4. Простые операции ===
a + b: [5 7 9]
a * 2: [2 4 6]
=== 5. Статистики ===
mean: 5.5
std: 2.8722813232690143
sum: 55
